### PR TITLE
TAStudio for Mono (and optionally Windows) (using GDI+)

### PR DESCRIPTION
**Pull request by Asnivor**
### MERGED
Bulk of the work has been done. Any bugs can be looked at downstream.

### CODE REVIEW

**Comment by YoshiRulz** [comment]
Byoutiful.

**Comment by Asnivor** [comment]
Nice :)

So it looks like the cell colour backgrounds are only being drawn for generic player2 controls and the Frame# column. At this point I have no idea why this would be the case, but i'll try and have a look at some point if I have the time this weekend.

For my reference (or if anyone wants to look into it in the mean time) this is the function that colours the cells:

https://github.com/Asnivor/BizHawk/blob/gdi_bidnis/BizHawk.Client.EmuHawk/CustomControls/InputRoll.Drawing.GDIP.cs#L460

Once we get that sorted (and dont find any bugs/crashes anywhere else in TAStudio) then we can merge.

**Comment by vadosnaprimer** [comment]
Amazing! So how will you do it, gdi and gdi+ will be 2 options for tastudio? I'll test it when you finish. Please don't merge without my approval.

**Comment by YoshiRulz** [comment]
@vadosnaprimer it's merging into MoreUnixMonoCompatWork, not master

**Comment by Asnivor** [comment]
@vadosnaprimer 

At the moment this is the key piece:

https://github.com/Asnivor/BizHawk/blob/a3f266e07bd6f173ee67d9388e36498a47366619/BizHawk.Client.EmuHawk/CustomControls/InputRoll.cs#L19

Obviously the  `= true` override here is for testing, to enable us to test this branch on both linux and windows. I was planning on initially just having linux as gdi+ and windows as gdi, but I guess we could put a config option in to force gdi+ on windows. Where would you want this to live though? In tasstudio, or bizhawk proper? (and in either case, where exactly?)

Also, as @YoshiRulz said.

This is a PR that will merge a branch, into another branch of a fork that is not going to touch the tasvideos/bizhawk repo yet. 

When it works enough, we it will be merged into the MoreUnixMonoCompatWork branch of my fork, at which point it will show up in this wip PR:

https://github.com/TASVideos/BizHawk/pull/1441

that when merged, will go into the MoreUnixMonoCompatWork branch on the official repo.

At this point, this:  https://github.com/TASVideos/BizHawk/pull/1438

will need to be approved by you and everyone else.

Its slightly more complex than I would like, and I'm not really sure how we got here. But this is how everything is right now :)

**Comment by vadosnaprimer** [comment]
If it can be changed on the fly, put it to tastudio Settings (nearby Rotate, which doesn't fully work).

And regardless of where it's merged to, I need to check it before it is, since checking is supposed to be done before merging, not after. I just have a lot of situations to test it in, and know how it's supposed to work.

**Comment by Asnivor** [comment]
TAStudio will need restarting if the renderer is changed on the fly, but I guess we can just pop a gui message in the usual way.

So rotate on linux seems to work (from my laymans point of view). Except when you click it a second time to rotate back. That causes  an exception that I need to look into.

> And regardless of where it's merged to, I need to check it before it is

No worries. We'll let you know when you can test.

**Comment by Asnivor** [comment]
@YoshiRulz 

Right, I think this is now done from my end. The 'missing cell background' stuff is now sorted:

**Windows:**
image

**Linux**
image


And on windows we can now select the renderer to use:
image

image

image


Whereas this is forced and handled in linux:
image

The chosen TAStudio renderer option is stored in Global.Config and defaults to 0 (GDI) on both windows and linux (but is forced to 1 when TAStudio opens on linux).

@YoshiRulz Please build and test in linux. I have done so (and all looks good) but would like to have a second *nix opinion.

@vadosnaprimer Please clone my fork:  https://github.com/asnivor/bizhawk
and build the `gdi_bidnis` branch: https://github.com/Asnivor/BizHawk/tree/gdi_bidnis

Let me know if anything isn't functioning like it should. Hopefully this will not be the case though, as all I have really done is abstracted the GDI drawing methods away to new GDI+ methods. None of the underlying TAStudio or InputRoll logic has been touched.

Windows performance-wise I am seeing very little difference between the two (whilst debugging anyway). GDI is maybe 1-3FPS quicker than GDI+.

When you are happy, I will merge this into the MoreUnixCompatWork branch in my fork. At this point, @YoshiRulz and I have made so much progress it is about time we merged the MoreUnixCompatWork branch on my fork into the MoreUnixCompatWork branch on tasvideos/bizhawk and update the PR comments there. I stress, we are not planning to merge to master yet as there are still a few bits to tackle. But the branch on the official repo really needs to come up to date (the only reason we are not working directly there is that yoshi doesnt have tasvideos organisation access).

Thanks,

-Asni

**Comment by vadosnaprimer** [comment]
Grabbed. Will see within a week.

Suggestions (as they come to mind):
- Remove "Options" from the menu name
- Make the font look match between renderers

Otherwise everything looks good.

**Comment by Asnivor** [comment]
@vadosnaprimer 

Ok, I think i've done all I can do for the moment. Row heights and cell sizes have been modified in GDI+ to match the GDI implementation. The only thing I _can'_t do at the moment, is change the text font width in GDI+ (as this is the remaining difference between the two I think). 

In GDI this is done with native calls that use LOGFONT methods to create a custom width:

https://github.com/Asnivor/BizHawk/blob/gdi_bidnis/BizHawk.Client.EmuHawk/CustomControls/Win32GDIRenderer.cs#L143

But I can't find a way to do this without touching win32 native stuff.

**GDI Renderer (Windows):**
image

**GDI+ Renderer (Windows):**
image

**GDI+ Renderer (Linux - Ubuntu 18.04):**
image

**Pull request merged**
