### PR TITLE
EmuHawk: Implement OpenTK controllers on unix - also tested and working on Windows (but disabled for now)

### PR DESCRIPTION
**Pull request by Asnivor**
## DO NOT MERGE YET

There is still much to be done with this (and it is setup to use OTK_Gamepad on windows).

@YoshiRulz 

Can you build and test this branch when you have a second? Unfortunately the OpenTK GamePadConfigurationDatabase doesn't have a mapping for my controller (in fact it doesnt have that many mappings at all: https://github.com/opentk/opentk/blob/master/src/OpenTK/Input/GamePadConfigurationDatabase.cs#L33), so many of the buttons are round the wrong way. I would be interested to see how it plays with your xbone controller.

If some of the mappings are swapped, it would be good if you could tell me how they are swapped (and hopefully they will be similar to mine if wrong).

If you could also check the terminal/output window, I have it writing some gamepad related info. eg. on mine this is:

```
Initialised OpenTK GamePad: Joystick 0 (Unmapped Controller)
OpenTK Mapping: Unmapped Controller
```

### CODE REVIEW

**Comment by Asnivor** [comment]
ok, reworking this now to leverage the OpenTK.Input.Joystick class as well (if the gamepad is not auto-mapped)

**Comment by Asnivor** [comment]
Right, I think thats done now. If the gamepad guid is recognised in the internal OpenTK database, then we use OpenTK.Input.GamePad to automap the controls (in a fashion similar to XInput on windows). If guid was not recognised, then we fall back to the OpenTK.Input.Joystick class and do it in a similar way to SlimDX DirectX (enumerating the buttons, hats and axis).

I'll have to test with a second gamepad (hopefully one that is recognised) in the morning, but i'm fairly hopeful. The axis thresholds may need tweaking though.

@YoshiRulz test away when you are ready

**Comment by YoshiRulz** [comment]
xbone: 11 working buttons, 0 working axes, no dpad (though I'm seeing this in the terminal when I go to bind something:
```
Bind Event: Release:WMouse L 
Unpressing X1 POV1D
Unpressing X1 POV1L
```
)
```
OTK GamePad/Joystick index: 0
Initialising OpenTK GamePad: 03000000-5e04-0000-ea02-000001030000
OpenTK Mapping: Unmapped Controller
```

x360: 11 working buttons, 5 working axes (couldn't get C-left, probably old HW), working dpad
```
OTK GamePad/Joystick index: 0
Initialising OpenTK GamePad: 03000000-5e04-0000-8e02-000014010000
OpenTK Mapping: X360 Controller
```

Steam controller (via Steam Big Pitcture with custom .desktop): nothing

I have a PS3 controller but no drivers and Wiimotes but no bluetooth and no USB adapter.

Unfortunately, the controller does have to be plugged in before starting EmuHawk (most, if not all, Steam games do this).

You should probably not use `X#` for Linux in case someone dual boots. Pretty sure it's using `libinput` so `L#`? Other than that great work!

**Review by YoshiRulz — APPROVED** [review]
forgot how reviews work, see comment

**Comment by Asnivor** [comment]
Yup, i've finally been able to test and the OpenTK.Input.Joystick stuff isn't working here either. But it looks like OpenTK.Input.GamePad *is* working (as your 360 controller was mapped properly).

I'll try and get that sorted. 

Regarding X#, I just copied the GamePad360 naming scheme for OpenTK.Input.Gamepad and the GamePad naming scheme for OpenTK.Input.Joystick so that the default bizhawk bindings may work out of the box. As we may eventually use OpenTK for windows also, L# doesnt make much sense. Maybe i'll use T# and update the default.json with the additional mappings.

**Comment by YoshiRulz** [comment]
can I test that ^

**Comment by Asnivor** [comment]
@YoshiRulz YES! I think its about done now. Test away!

I have kept the X# identifiers as this should make the bizhawk default controls (defctrl.json) work in a lot of cases without changing anything.

Anyway, this is just part of a string value that is stored in the config file when folks set their controls. I doubt this would be causing any problems on linux.

**Comment by YoshiRulz** [comment]
testing now, assuming it all works resolves TASVideos#1103

**Comment by YoshiRulz** [comment]
Xbone works perfectly, though I had difficulties binding the A-stick (axes X and Y), probably not something we can fix. X360 doesn't work at all, and I'll be damned if I'm setting up the Steam controller again.

Edit: at this point I say merge and move on to something else, Linux users can figure out AntiMicro.

**Comment by Asnivor** [comment]
Weird, the x360 *was* working before right?

I'll test tonight with my wired 360 controller. Probably a simple mistake that I can't see right now.

And the Xbone A-stick - it is possible it is using a weird axis index, and I need to add more in (iirc opentk supports 64 axis in joystick.cs)

**Comment by YoshiRulz** [comment]
The axes were definitely *working*, it just really liked X-.

**Comment by Asnivor** [comment]
Can you test again?

**Comment by YoshiRulz** [comment]
~~shoulda squashed~~ nm just saw the unmerge button

**Comment by Asnivor** [comment]
Balls :( ill leave that to you then :)

**Comment by YoshiRulz** [comment]
already done

**Pull request merged**
