### PR TITLE
MemoryBlock abstraction

### PR DESCRIPTION
**Pull request by YoshiRulz**
* [x] compiles
* [x] no regressions on Windows
* [x] no regressions on Linux
* [ ] extra cores now work: BSNES, Genplus-gx, NeoPop, SameBoy, Saturnus, Snes9x

### CODE REVIEW

**Comment by YoshiRulz** [comment]
Upon loading *Sonic the Hedgehog Pocket Adventure* for the Neo Geo Pocket:
```
A core accepted the rom, but threw an exception while loading it:

System.BadImageFormatException: Method has zero rva
File name: 'BizHawk.Common'
	at BizHawk.Common.BizInvoke.MemoryBlockUnix..ctor (System.UInt64 start, System.UInt64 size) [0x00032] in <b1494634261f4b1b81693bbe24695cc5>:0 
	at BizHawk.Emulation.Cores.Waterbox.PeWrapper..ctor (System.String moduleName, System.Byte[] fileData, System.UInt64 destAddress) [0x0031d] in <6e23884d528946b8bc6041dbf0cf5ae1>:0 
	at BizHawk.Emulation.Cores.Waterbox.PeRunner..ctor (BizHawk.Emulation.Cores.Waterbox.PeRunnerOptions opt) [0x0019a] in <6e23884d528946b8bc6041dbf0cf5ae1>:0 
	at BizHawk.Emulation.Cores.Waterbox.WaterboxCore.PreInit[T] (BizHawk.Emulation.Cores.Waterbox.PeRunnerOptions options) [0x00025] in <6e23884d528946b8bc6041dbf0cf5ae1>:0 
	at BizHawk.Emulation.Cores.Consoles.SNK.NeoGeoPort..ctor (BizHawk.Emulation.Common.CoreComm comm, System.Byte[] rom, BizHawk.Emulation.Cores.Consoles.SNK.NeoGeoPort+SyncSettings syncSettings, System.Boolean deterministic, System.UInt64 startAddress) [0x000d6] in <6e23884d528946b8bc6041dbf0cf5ae1>:0 
	at BizHawk.Emulation.Cores.Consoles.SNK.NeoGeoPort..ctor (BizHawk.Emulation.Common.CoreComm comm, System.Byte[] rom, BizHawk.Emulation.Cores.Consoles.SNK.NeoGeoPort+SyncSettings syncSettings, System.Boolean deterministic) [0x00000] in <6e23884d528946b8bc6041dbf0cf5ae1>:0 
	at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)
	at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in <eabff256da0b4c4db432852f93333375>:0 
```

**Comment by YoshiRulz** [comment]
Upon loading *Sonic the Hedgehog Pocket Adventure* for the Neo Geo Pocket:
```
A core accepted the rom, but threw an exception while loading it:

System.InvalidOperationException: mmap() returned NULL
	at BizHawk.Common.BizInvoke.MemoryBlockUnix.Activate () [0x0004e] in <cfb171a0e69d45aa8f9ec0484d643a1b>:0
	at BizHawk.Emulation.Cores.Waterbox.PeWrapper..ctor (System.String moduleName, System.Byte[] fileData, System.UInt64 destAddress) [0x00300] in <4f05b1ab2b914fadb1dc61106df2a909>:0
	at BizHawk.Emulation.Cores.Waterbox.PeRunner..ctor (BizHawk.Emulation.Cores.Waterbox.PeRunnerOptions opt) [0x0017c] in <4f05b1ab2b914fadb1dc61106df2a909>:0
	at BizHawk.Emulation.Cores.Waterbox.WaterboxCore.PreInit[T] (BizHawk.Emulation.Cores.Waterbox.PeRunnerOptions options) [0x0001e] in <4f05b1ab2b914fadb1dc61106df2a909>:0
	at BizHawk.Emulation.Cores.Consoles.SNK.NeoGeoPort..ctor (BizHawk.Emulation.Common.CoreComm comm, System.Byte[] rom, BizHawk.Emulation.Cores.Consoles.SNK.NeoGeoPort+SyncSettings syncSettings, System.Boolean deterministic, System.UInt64 startAddress) [0x000cb] in <4f05b1ab2b914fadb1dc61106df2a909>:0
	at BizHawk.Emulation.Cores.Consoles.SNK.NeoGeoPort..ctor (BizHawk.Emulation.Common.CoreComm comm, System.Byte[] rom, BizHawk.Emulation.Cores.Consoles.SNK.NeoGeoPort+SyncSettings syncSettings, System.Boolean deterministic) [0x00000] in <4f05b1ab2b914fadb1dc61106df2a909>:0
	at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)
	at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in <eabff256da0b4c4db432852f93333375>:0
```

**Comment by Asnivor** [comment]
Cores tested on windows (with no obvious regressions):

* BSNES
* Snes9x
* Genplus-gx
* NeoPop
* Saturnus
* Octoshock

They all load and basic memory tool tests (RamWatch, RamSearch) function correctly

Not entirely sure how to test SameBoy....

**Comment by YoshiRulz** [comment]
So MemoryBlockWin32 is good, MemoryBlockUnix isn't.

**Comment by nattthebear** [comment]
It's your fork and I don't control it, but I'd like to offer an opinion:  I think 6d79385abc6c2 isn't the greatest.  MemoryBlock encapsulates its work and could work on many different systems with the implementations to do it, and is a bit ugly in order to accomplish all of that.  But that commit smears the ugliness all over; everywhere that would instantiate a MemoryBlock now has to know about different kinds of MemoryBlock impls and which one would be needed.  Even if all of the `new MemoryBlock` callsites were handled with `#ifdef`, it would still be spreading that knowledge all over instead of encapsulating it.

**Comment by nattthebear** [comment]
So, `mmap` isn't working.  A few thoughts:
1. That error message isn't actually accurate; it will show if `mmap` returns anything other than the exactly requested pointer.
2. At the callsite to `mmap`, what are all of the parameters?  Do they make sense?
3. What is `mmap` returning?

I wonder if I'm missing an `ftruncate` call or similar after calling `memfd_open`?

**Comment by YoshiRulz** [comment]
@nattthebear I was thinking about the double constructors, moving those to two helper methods called like `MemoryBlock.PlatformConstructor(start, len)` was the alternative I came up with.

Also I literally changed nothing about the mmap calls except adding DllImport, taking another look now. Edit: (still loading *Sonic*) mmap returns `-1`, `Z.US(Start)` should be `3775276253184`.

**Comment by nattthebear** [comment]
Right, but I never even tried those calls so who says if they work?  Heh.

I think `ftruncate` would be the next thing to try, it's probably needed on the fd right after `memfd_open`

**Comment by YoshiRulz** [comment]
Like this?
```csharp
_fd = Kernel.memfd_create("MemoryBlockUnix", 0);
if (_fd == -1) throw new InvalidOperationException("memfd_create() returned -1");
Kernel.ftruncate(_fd, size);
```
Same error.

**Comment by nattthebear** [comment]
I'd need to get into it next probably.  No idea what's going on there.

**Comment by YoshiRulz** [comment]
Merging this into `MoreUnixMonoCompatWork` as there are no regressions on Windows.

**Pull request merged**
